helmDefaults:
  args: []
  diffArgs:
    - "--suppress-secrets"
  wait: true
  timeout: 1800
  waitForJobs: true
  deleteWait: true
  deleteTimeout: 300

repositories:
  - name: jetstack
    url: https://charts.jetstack.io

releases:
  - name: cert-manager
    namespace: cert-manager
    installed: true
    chart: jetstack/cert-manager
    version: v1.17.1
    createNamespace: true
    values:
      - cert-manager/values.yaml.gotmpl

  - name: trust-manager
    namespace: cert-manager
    installed: true
    chart: jetstack/trust-manager
    version: 0.16.0
    createNamespace: true
    needs:
      - cert-manager/cert-manager
    values:
      - trust-manager/values.yaml.gotmpl

  - name: cert-customizations
    namespace: cert-manager
    installed: true
    chart: cert-customizations
    createNamespace: true
    needs:
      - cert-manager/trust-manager
    values:
      - {{- toYaml .Values | nindent 8 }}
