{{- if not .Values.global.tls.ca.selfSigned }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.tls.ca.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: "Helm"
    meta.helm.sh/release-name: {{ .Release.Name | quote }}
type: Opaque
data:
  tls.crt: {{ .Files.Get "assets/ca.crt" | b64enc }}
  tls.key: {{ .Files.Get "assets/ca.key" | b64enc }}
{{- end }}
