{{- if not .Values.caConfig.useSelfSigned }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cert-bundle
  namespace: cert-manager
type: Opaque
data:
  tls.crt: {{ .Files.Get "assets/ca.crt" | b64enc }}
  bundle.pem: {{ .Files.Get "assets/trusted-ca-bundle.pem" | b64enc }}
{{- end }}
