{{- if (tpl .Values.tls.ca.selfSigned .) }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: self-signed-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: self-signed-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: local.dev
  secretName: {{ tpl .Values.tls.ca.secretName . }}
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: self-signed-issuer
    kind: ClusterIssuer
    group: cert-manager.io
{{- end }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ tpl .Values.tls.ca.issuerName . }}
spec:
  ca:
    secretName: {{ tpl .Values.tls.ca.secretName . }}
