environments:
  default:
    values:
      - config.yaml
      - values.yaml
      - secrets.yaml
      - environments/k3d.yaml
  k3d:
    values:
      - config.yaml
      - values.yaml
      - secrets.yaml
      - environments/k3d.yaml
  k3s:
    values:
      - config.yaml
      - values.yaml
      - secrets.yaml
      - environments/k3s.yaml
---
lockFilePath: helmfile.lock

helmDefaults:
  args: []
  diffArgs:
    - "--suppress-secrets"
  wait: true
  timeout: 1800
  waitForJobs: true
  deleteWait: true
  deleteTimeout: 300
  createNamespace: true

templates:
  default:
    valuesTemplate:
      - global: {{ .Values.global | toYaml | nindent 10 }}
        secrets: {{ .Values.secrets | toYaml | nindent 10 }}

repositories:
  - name: jetstack
    url: https://charts.jetstack.io
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: traefik
    url: https://traefik.github.io/charts
  - name: coredns
    url: https://coredns.github.io/helm

releases:
  - name: ingress-controller
    namespace: kube-system
    installed: {{ .Values | get "apps.ingress-controller.enabled" }}
    chart: apps/ingress-controller
    values:
      - apps/ingress-controller/{{ get "apps.ingress-controller.type" .Values }}/values.yaml
      - {{  get "apps.ingress-controller.type" .Values }}:
          enabled: true

  - name: cert-manager
    namespace: cert-manager
    installed: {{ .Values | get "apps.cert-manager.enabled" }}
    chart: jetstack/cert-manager
    version: v1.17.1
    values:
      - apps/cert-manager/values.yaml

  - name: trust-manager
    namespace: cert-manager
    installed: {{ .Values | get "apps.trust-manager.enabled" }}
    chart: jetstack/trust-manager
    version: 0.16.0
    needs:
      - cert-manager/cert-manager
    values:
      - apps/trust-manager/values.yaml

  - name: ca-certs
    namespace: cert-manager
    installed: {{ .Values | get "apps.ca-certs.enabled" }}
    chart: apps/ca-certs
    inherit:
      - template: default
    needs:
      - cert-manager/trust-manager
    values:
      - apps/ca-certs/values.yaml.gotmpl
      - {{ .Values | get "apps.ca-certs" | toYaml | nindent 8 }}

  - name: grafana
    namespace: monitoring
    installed: {{ .Values | get "apps.grafana.enabled" }}
    chart: grafana/grafana
    version: 8.10.4
    inherit:
      - template: default
    values:
      - apps/grafana/values.yaml.gotmpl
      - {{ .Values | get "apps.grafana" | toYaml | nindent 8 }}

  - name: loki
    namespace: monitoring
    installed: {{ .Values | get "apps.loki.enabled" }}
    chart: grafana/loki
    version: 6.29.0
    inherit:
      - template: default
    values:
      - apps/loki/values.yaml.gotmpl
      - {{ .Values | get "apps.loki" | toYaml | nindent 8 }}

  - name: alloy
    namespace: monitoring
    installed: {{ .Values | get "apps.alloy.enabled" }}
    chart: grafana/alloy
    version: 0.12.5
    inherit:
      - template: default
    values:
      - apps/alloy/values.yaml.gotmpl
      - {{ .Values | get "apps.alloy" | toYaml | nindent 8 }}

  - name: dnsserver
    namespace: nameserver
    installed: {{ .Values | get "apps.dnsserver.enabled" }}
    chart: apps/dnsserver
    inherit:
      - template: default
    values:
      - apps/dnsserver/values.yaml.gotmpl
      - {{ .Values | get "apps.dnsserver" | toYaml | nindent 8 }}

  - name: cluster
    installed: {{ getOrNil "installed" .Values | default false }}
    chart: cluster/{{ .Environment.Name }}
    version: 0.1.0
    values:
      - config.yaml
    postRenderer: tee
    postRendererArgs:
      - cluster/config.yaml
