#!/usr/bin/env sh
PROJROOT=$(dirname $(realpath $BASH_SOURCE[0]))
docker run \
    --rm \
    --env-file .env \
    --network host \
    --security-opt seccomp=unconfined \
    --security-opt label=disable \
    -v $PROJROOT:$PROJROOT \
    -v $HOME:$HOME:ro \
    -v $HOME/.cache/helm:/helm/.cache/helm \
    -v $HOME/.config/helm:/helm/.config/helm \
    -v $HOME/.kube/config:/helm/.kube/config:ro \
    -it \
    -w $PROJROOT \
    ghcr.io/helmfile/helmfile:v0.171.0 $@
