cert-manager:
  enabled: true
trust-manager:
  enabled: true
ca-certs:
  enabled: true
grafana:
  enabled: true
loki:
  enabled: true
alloy:
  enabled: true
ingress-controller:
  enabled: true
  type: "traefik" # ingress-nginx, traefik
dnsserver:
  enabled: true
  zones: []
    # - rootDomain: "nncorp.home"
    #   ttl: 5m
    #   soa:
    #     rootNameserver: ns.nncorp.home.
    #     maintainer: admin.nncorp.home
    #     serial: 2020010511
    #     peerIntervals:
    #       refresh: 1d
    #       retry: 2h
    #       expiration: 4w
    #     cacheExpiration: 1h
    #   records:
    #     - name: "@"
    #       entries:
    #         - { "class": "IN", "type": "NS", "value": "ns.nncorp.home" }
    #         - { "class": "IN", "type": "A", "value": "172.28.0.2" }
    #         - { "class": "IN", "type": "A", "value": "172.28.0.3" }
    #         - { "class": "IN", "type": "A", "value": "172.28.0.4" }
    #     - name: "ns"
    #       entries:
    #         - { "class": "IN", "type": "CNAME", "value": "@" }
    #     - name: "monitoring"
    #       entries:
    #         - { "class": "IN", "type": "CNAME", "value": "@" }
  extraZones:
    - rootDomain: "{{ .Values.global.cluster.hostname }}"
      ttl: 5m
      soa:
        rootNameserver: "ns.{{ .Values.global.cluster.hostname }}"
        maintainer: "admin.{{ .Values.global.cluster.hostname }}"
        serial: 2020010510
        peerIntervals:
          refresh: 1d
          retry: 2h
          expiration: 4w
        cacheExpiration: 1h
      records:
        - name: "@"
          entries:
            - { "class": "IN", "type": "NS", "value": "ns.{{ .Values.global.cluster.hostname }}" }
            - { "class": "IN", "type": "A", "value": "172.28.0.2" }
            - { "class": "IN", "type": "A", "value": "172.28.0.3" }
            - { "class": "IN", "type": "A", "value": "172.28.0.4" }
        - name: "ns"
          entries:
            - { "class": "IN", "type": "CNAME", "value": "@" }
        - name: "monitoring"
          entries:
            - { "class": "IN", "type": "CNAME", "value": "@" }
