token: "provenance"
write-kubeconfig-mode: "0644"
tls-san:
  - {{ .Values.infra.rootDomain }}
cluster-init: true
{{- $disabledServices := list -}}
{{- if not .Values.deployment.cluster.services.ingressController -}}
{{- $disabledServices = append $disabledServices "traefik" -}}
{{- end }}
{{- if not .Values.deployment.cluster.services.metricsServer -}}
{{- $disabledServices = append $disabledServices "metrics-server" -}}
{{- end }}
{{- if not .Values.deployment.cluster.services.storageProvisioner }}
{{- $disabledServices = append $disabledServices "local-storage" -}}
{{- end }}
{{- if not .Values.deployment.cluster.services.loadBalancer }}
{{- $disabledServices = append $disabledServices "servicelb" -}}
{{- end }}
{{- if gt (len $disabledServices) 0 }}
disable:
{{- $disabledServices | toYaml | nindent 2 }}
{{- end }}
