environments:
  default:
    values:
      - values.yaml
---
helmDefaults:
  args: []
  diffArgs:
    - "--suppress-secrets"
  wait: true
  timeout: 1800
  waitForJobs: true
  deleteWait: true
  deleteTimeout: 300

repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: grafana
    namespace: monitoring
    chart: grafana/grafana
    createNamespace: true
    values:
      - grafana/values.yaml.gotmpl
      - {{- toYaml .Values.global | nindent 8 }}

  - name: loki
    namespace: monitoring
    chart: grafana/loki
    createNamespace: true
    installed: true
    values:
      - loki/values.yaml.gotmpl
      - {{- toYaml .Values.global | nindent 8 }}
