{{- if not .Values.caConfig.selfSigned }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.caConfig.secret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ca-certs.labels" . | nindent 4 }}
type: Opaque
data:
  tls.crt: {{ .Files.Get "assets/ca.crt" | b64enc }}
  tls.key: {{ .Files.Get "assets/ca.key" | b64enc }}
{{- end }}
