{{- if not .Values.caConfig.selfSigned }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.caConfig.secret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ca-certs.labels" . | nindent 4 }}
type: Opaque
data:
  tls.crt: {{- .Values.secrets.tls.ca.certificate | trim | printf "%s\n"| b64enc | indent 1 }}
  tls.key: {{- .Values.secrets.tls.ca.privateKey | trim | printf "%s\n"| b64enc | indent 1 }}
{{- end }}
