{{- if .Values.caConfig.selfSigned }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: self-signed-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: self-signed-ca
  namespace: {{ .Release.Namespace }}
spec:
  isCA: true
  commonName: {{ .Values.caConfig.commonName }}
  secretName: {{ .Values.caConfig.secret.name }}
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: self-signed-issuer
    kind: ClusterIssuer
    group: cert-manager.io
{{- end }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.caConfig.issuer.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ca:
    secretName: {{ .Values.caConfig.secret.name }}
