{{- if .Values.coredns.deployment.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ .Values.commonLabels | toYaml | nindent 4 }}
  annotations:
    {{ .Values.commonAnnotations | toYaml | nindent 4 }}
data:
  Corefile.override: |
    log
  {{- range $index, $zoneData := (concat .Values.zones .Values.extraZones) }}
  {{ tpl $zoneData.rootDomain $ }}.server: |
    {{ tpl $zoneData.rootDomain $ }}:53 {
      file /etc/coredns/custom/db.{{ tpl $zoneData.rootDomain $ }}
      log
      errors
    }
  db.{{ tpl $zoneData.rootDomain $ }}: |
    $ORIGIN {{ tpl $zoneData.rootDomain $ }}
    $TTL {{ $zoneData.ttl }}

    @    IN    SOA    {{ tpl $zoneData.soa.rootNameserver $ }}. {{ tpl $zoneData.soa.maintainer $ }}. (
                            {{ int $zoneData.soa.serial | printf "%d" }}
                            {{ printf "%s" $zoneData.soa.peerIntervals.refresh }}
                            {{ printf "%s" $zoneData.soa.peerIntervals.retry }}
                            {{ printf "%s" $zoneData.soa.peerIntervals.expiration }}
                            {{ printf "%s" $zoneData.soa.cacheExpiration }})
    {{- range $recordIndex, $recordData := $zoneData.records }}
    {{- range $entryIndex, $entryData := $recordData.entries }}
    {{ tpl $recordData.name $ }}    {{ tpl $entryData.class $ }}    {{ tpl $entryData.type $ }}    {{ tpl $entryData.value $ }}
    {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
