environments:
  default:
    values:
      - values.yaml
      - secrets.yaml
---
helmDefaults:
  args: []
  diffArgs:
    - "--suppress-secrets"
  wait: true
  timeout: 1800
  waitForJobs: true
  deleteWait: true
  deleteTimeout: 300

values:
  - env.yaml.gotmpl

helmfiles:
  - path: tls-management/helmfile.yaml
    values:
      - {{- toYaml .Values | nindent 8 }}

  - path: monitoring/helmfile.yaml
    values:
      - {{- toYaml .Values | nindent 8 }}

  - path: cluster/helmfile.yaml
    values:
      - {{- toYaml .Values | nindent 8 }}
