---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dnsserver-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dnsserver.helm_labels" . | indent 4 }}
  annotations:
    {{- include "dnsserver.helm_annotations" . | indent 4 }}
data:
  deug: |-
    {{ .Values | toYaml | nindent 4 }}
  Corefile.override: |
    forward . 8.8.8.8
    log
  {{- range $index, $zoneData := (concat .Values.dnsserver.zones .Values.dnsserver.extraZones) }}
  {{ $zoneData.rootDomain }}.server: |
    {{ $zoneData.rootDomain }}:53 {
      file /etc/coredns/custom/db.{{ $zoneData.rootDomain }}
      log
      errors
    }
  db.{{ $zoneData.rootDomain }}: |
    $ORIGIN {{ $zoneData.rootDomain }}
    $TTL {{ $zoneData.ttl }}

    @    IN    SOA    {{ $zoneData.soa.rootNameserver }}. {{ $zoneData.soa.maintainer }}. (
                            {{ int $zoneData.soa.serial | printf "%d" }}
                            {{ printf "%s" $zoneData.soa.peerIntervals.refresh }}
                            {{ printf "%s" $zoneData.soa.peerIntervals.retry }}
                            {{ printf "%s" $zoneData.soa.peerIntervals.expiration }}
                            {{ printf "%s" $zoneData.soa.cacheExpiration }})
    {{- range $recordIndex, $recordData := $zoneData.records }}
    {{- range $entryIndex, $entryData := $recordData.entries }}
    {{ $recordData.name }}    {{ $entryData.class }}    {{ $entryData.type }}    {{ $entryData.value }}
    {{- end }}
    {{- end }}
  {{- end }}
