helmDefaults:
  args: []
  diffArgs:
    - "--suppress-secrets"
  wait: true
  timeout: 1800
  waitForJobs: true
  deleteWait: true
  deleteTimeout: 300

repositories:
  - name: traefik
    url: https://traefik.github.io/charts
  - name: coredns
    url: https://coredns.github.io/helm

values:
  - values.yaml

releases:
  - name: dnsserver
    namespace: nameserver
    chart: dnsserver
    createNamespace: true
    installed: {{ .Values.dnsserver.enabled }}
    values:
      - dnsserver/values.yaml
      - values.yaml.gotmpl
